# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AxCYU8dgK0LawQqyD7V4ZtEA0BmGZ6QB
"""

mystring = "hello"

abdul_rafay = 5

"""# New Section"""

print(abdul_rafay)

abdul_rafay =("AI Basic course")

multiply=(3,6)

print(3*6)

print('abdulrafay')

a = 'abdul rafay'
print(a)

a = 'abdul rafay'
print(a.upper())

a = 'RAFAY MALIK'
print(a.lower())

a = " skills! "
print(a.strip())

a = 'rafay malik'
print(a.replace("malik","abdul"))

a = 'malik, rafay'
print(a.split(","))

a = 'abdul rafay'
print(a.upper())

captilize_text = "ABDUL RAFAY"

print(captilize_text)

thislist = 'abdul','rafay','malkik'
print(thislist)

print(len(thislist))

list1 = ("abc" ,56 ,True , "male")

malik = 'rafay'

print(malik)

print(a.upper())

print(a.lower())

list1 = ['apple', 'banana','cherry']

print(list1[-1])

list1.append(5)
print(list1)

a = 'malik rafay'
print(a.replace('malik','abdul'))

a = 'rafay malik'
print(a.replace("malik","abdul"))

thistuple = ("apple","banana", "cherry" )
print(thistuple)

thistuple = ("apple",)
print(type(thistuple))

thistuple = ("apple")
print(type(thistuple))

thisset = {"apple", "banana","cherry",}
 print(thisset)

print(thisset[0])



thisset = ("apple", "banana", "cherry")
print(len(thisset))

thisdic = {"samsung": "galaxya32", "dell": "laptop", "year": "2017"}
print(thisdic)



thisdic = {
    "samsung": "galaxya32",
    "dell": "laptop",
    "year": "2017",
}
print(thisdic["year"])

thisdic["year"]="2016"

print(thisdic)

"""List1

"""

list1 = ["apple","banana", "cherry"]
print(list1)

"""Tuple

"""

thistuple = ("apple","banana","cherry")
print(thistuple)

thisdic = {"apple","banana", "cherry"}
print(thisdic)

thisset = {"samsung": "a32", "dell": "laptop","model":"2016"}
print(thisset["samsung"])

thisdic = {
    "samsung": "s22",
    "dell": "laptop",
    "model": "2016",
}

print(thisdic["model"])

a = ("apple")
print(a.upper)

given_number = 3

if given_number > 6:

    print("The square of", given_number, "is:", square_result)

print('Next Lines of code')

#ham check ker rahe hain codding ko
num1, num2 = 5, 6
if(num1 < num2) : print("num1 is less than num2")

student_grade = 60

if student_grade >= 65:
    print("student has scored passing grade")
else:
    print("student has scored failing garde")

given_number = input("Please inter any number: ")

if int(given_number) > 0:
    print(given_number, "is Positive")

elif int(given_number) == 0:
    print(given_number, "is zero")

else:

    print(given_number, "is a negative")

password_check= input(" inter password : ")

if ("password_check") == "Rafay":
    print(password_check, "correct password")

else:
    print(password_check, "Incorect password")

password_check = input("Enter password: ")

if password_check == "Malik":
    print(password_check, "Correct password")
else:
    print(password_check, "Incorrect password")

password_check = input("Enter password: ")

if password_check == "python@99>":
    print(password_check, "Correct password")
elif password_check != "python@99>":
    print(password_check, "Incorrect password")

num1 = 89
num2 = 90
print(num1%num2)

import random

def guessing_game():
    print("Welcome to the Guessing Game!")
    secret_number = random.randint(1, 100)
    attempts = 0

    while True:
        guess = int(input("Guess the secret number (between 1 and 100): "))
        attempts += 1

        if guess == secret_number:
            print(f"Congratulations! You guessed the correct number {secret_number} in {attempts} attempts.")
            break
        elif guess < secret_number:
            print("Too low! Try again.")
        else:
            print("Too high! Try again.")

if __name__ == "__main__":
    guessing_game()

malik_rafay = "rafaymalik"
print(malik_rafay.upper())

str1= "HELLO"
str2= "WORLD"
print(str1 + str2)

import random

def guessing_game():
    print("Welcome to the Guessing Game!")
    secret_number = random.randint(1, 100)
    attempts = 0

    while True:
        guess = int(input("Guess the secret number (between 1 and 100): "))
        attempts += 1

        if guess == secret_number:
            print(f"Congratulations! You guessed the correct number {secret_number} in {attempts} attempts.")
            break
        elif guess < secret_number:
            print("Too low! Try again.")
        else:
            print("Too high! Try again.")

if __name__ == "__main__":
    guessing_game()

import random

def guessing_game():
    print("Welcome to rafay ki game!")
    secret_number = random.randint(1,100)
    attempt = 0

    while True:
       guess = int(input("Guess the secret number between (1 and 100)"))
       attempt+= 1
       if   guess == secret_number:
            print(input(f"congradution! You Guessed the correct number bawa tusi great ho{secret_number} in {attempts} attempts."))
            break

       elif guess < secret_number:
            print("yeh to boht kam number hain dubara karein.")
       else :
            print("Yeh to boht zayda number hain dubara karein.")

if __name__ == "__main__":
    guessing_game()

import random

def guessing_game():
    print("Welcome to Rafay's game!")
    secret_number = random.randint(1, 100)
    attempts = 0

    while True:
        guess = int(input("Guess the secret number between 1 and 100: "))
        attempts += 1

        if guess == secret_number:
            print(f"Congratulations! You guessed the correct number {secret_number} in {attempts} attempts.")
            break
        elif guess < secret_number:
            print("This is too low! Try again.")
        else:
            print("This is too high! Try again.")

if __name__ == "__main__":
    guessing_game()

"""# LLA Application By Rafay

"""

pip install streamlit

# Commented out IPython magic to ensure Python compatibility.
# %%writefile calculator_app.py
# import streamlit as st
# 
# # Function to perform the calculation
# def calculate(num1, num2, operation):
#     if operation == 'Addition':
#         return num1 + num2
#     elif operation == 'Subtraction':
#         return num1 - num2
#     elif operation == 'Multiplication':
#         return num1 * num2
#     elif operation == 'Division':
#         if num2 != 0:
#             return num1 / num2
#         else:
#             return "Cannot divide by zero"
# 
# # Streamlit UI
# st.title("Simple Calculator")
# 
# # Input fields
# num1 = st.number_input("Enter the first number:", step=1)
# num2 = st.number_input("Enter the second number:", step=1)
# operation = st.selectbox("Select operation:", ['Addition', 'Subtraction', 'Multiplication', 'Division'])
# 
# # Calculate button
# if st.button("Calculate"):
#     result = calculate(num1, num2, operation)
#     st.success(f"Result: {result}")
#

!streamlit run calculator_app.py

!pip install streamlit

!streamlit deploy calculator_app.py