# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AxCYU8dgK0LawQqyD7V4ZtEA0BmGZ6QB

"""# LLA Application By Rafay

"""

pip install streamlit

# Commented out IPython magic to ensure Python compatibility.
# %%writefile calculator_app.py
# import streamlit as st
# 
# # Function to perform the calculation
# def calculate(num1, num2, operation):
#     if operation == 'Addition':
#         return num1 + num2
#     elif operation == 'Subtraction':
#         return num1 - num2
#     elif operation == 'Multiplication':
#         return num1 * num2
#     elif operation == 'Division':
#         if num2 != 0:
#             return num1 / num2
#         else:
#             return "Cannot divide by zero"
# 
# # Streamlit UI
# st.title("Simple Calculator")
# 
# # Input fields
# num1 = st.number_input("Enter the first number:", step=1)
# num2 = st.number_input("Enter the second number:", step=1)
# operation = st.selectbox("Select operation:", ['Addition', 'Subtraction', 'Multiplication', 'Division'])
# 
# # Calculate button
# if st.button("Calculate"):
#     result = calculate(num1, num2, operation)
#     st.success(f"Result: {result}")
#

!streamlit run calculator_app.py

!pip install streamlit

!streamlit deploy calculator_app.py
